name: "Kubernetes Deployment"

on:
  workflow_run:
    workflows: ["Build / Push docker image to ghcr"]
    types:
      - completed

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      # Creates local cluster on kind
      - uses: actions/checkout@v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0

      - name: Wait all cluster ready
        run: |
          kubectl wait nodes --for condition=Ready --all

      - name: App deployment and expose the port
        run: |
          kubectl create deployment flexport-app --image=ghcr.io/${{ github.repository }}:main
          kubectl wait pods --for condition=Ready --all --timeout=240s
          kubectl expose deployment/flexport-app --type=NodePort --port 5000

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test deployment
        run: |
          kubectl get services/flexport-app -o go-template='{{(index .spec.ports 0).nodePort}}'
          kubectl port-forward service/flexport-app 5000:5000 > /dev/null &

      - name: Run test
        run: |
          export APP_URL=http://localhost:5000
          PYTHONPATH="${PYTHON_PATH}:./src" coverage run -m  pytest -v tests/integration

      - name: Generate coverage report
        run: |
          coverage report -m

      - name: Delete cluster
        if: always()
        run: |
          kind delete cluster --name flexport-app
